### PR TITLE
Citizen Updates

### PR DESCRIPTION
**Pull request by NaomiMunyiri**
New Citizen Updates including changes on alert message form, landig page and functionalities

### CODE REVIEW

**Comment by NaomiMunyiri** [comment]
Admin Updates has updates in layout, and table viewing

**Comment by NaomiMunyiri** [comment]
Citizen and User Updates

**Comment by NaomiMunyiri** [comment]
Admin updates

**Comment by trevoromondi** [comment]
The functionality includes the messaging API that allows citizens to receive messages

**Comment by trevoromondi** [comment]
This packages enable the messaging API to work

**Comment by trevoromondi** [comment]
Incremental Changes

**Pull request merged**
